Update protect_key_files.yml

diff --git a/.github/workflows/protect_key_files.yml b/.github/workflows/protect_key_files.yml
--- a/.github/workflows/protect_key_files.yml
+++ b/.github/workflows/protect_key_files.yml
@@ -20,8 +20,15 @@ jobs:
 
           for file in "${protected_files[@]}"; do
             if echo "$changed_files" | grep -qE "^$file$"; then
-              echo "Error: $file has been modified!"
-              exit 1
+              modified_protected_files+=("$file")
             fi
           done
+
+          if [ ${#modified_protected_files[@]} -ne 0 ]; then
+            echo "Error: The following protected files have been modified:"
+            for file in "${modified_protected_files[@]}"; do
+              echo "- $file"
+            done
+            exit 1
+          fi
 
